INSERT INTO State(StateName) VALUES('Alabama');
INSERT INTO State(StateName) VALUES('Alaska');
INSERT INTO State(StateName) VALUES('Arizona');
INSERT INTO State(StateName) VALUES('Arkansas');
INSERT INTO State(StateName) VALUES('California');
INSERT INTO State(StateName) VALUES('Colorado');
INSERT INTO State(StateName) VALUES('Connecticut');
INSERT INTO State(StateName) VALUES('Delaware');
INSERT INTO State(StateName) VALUES('Florida');
INSERT INTO State(StateName) VALUES('Georgia');
INSERT INTO State(StateName) VALUES('Hawaii');
INSERT INTO State(StateName) VALUES('Idaho');
INSERT INTO State(StateName) VALUES('Illinois');
INSERT INTO State(StateName) VALUES('Indiana');
INSERT INTO State(StateName) VALUES('Iowa');
INSERT INTO State(StateName) VALUES('Kansas');
INSERT INTO State(StateName) VALUES('Kentucky');
INSERT INTO State(StateName) VALUES('Louisiana');
INSERT INTO State(StateName) VALUES('Maine');
INSERT INTO State(StateName) VALUES('Maryland');
INSERT INTO State(StateName) VALUES('Massachusetts');
INSERT INTO State(StateName) VALUES('Michigan');
INSERT INTO State(StateName) VALUES('Minnesota');
INSERT INTO State(StateName) VALUES('Mississippi');
INSERT INTO State(StateName) VALUES('Missouri');
INSERT INTO State(StateName) VALUES('Montana');
INSERT INTO State(StateName) VALUES('Nebraska');
INSERT INTO State(StateName) VALUES('Nevada');
INSERT INTO State(StateName) VALUES('New Hampshire');
INSERT INTO State(StateName) VALUES('New Jersey');
INSERT INTO State(StateName) VALUES('New Mexico');
INSERT INTO State(StateName) VALUES('New York');
INSERT INTO State(StateName) VALUES('North Carolina');
INSERT INTO State(StateName) VALUES('North Dakota');
INSERT INTO State(StateName) VALUES('Ohio');
INSERT INTO State(StateName) VALUES('Oklahoma');
INSERT INTO State(StateName) VALUES('Oregon');
INSERT INTO State(StateName) VALUES('Pennsylvania');
INSERT INTO State(StateName) VALUES('Rhode Island');
INSERT INTO State(StateName) VALUES('South Carolina');
INSERT INTO State(StateName) VALUES('South Dakota');
INSERT INTO State(StateName) VALUES('Tennessee');
INSERT INTO State(StateName) VALUES('Texas');
INSERT INTO State(StateName) VALUES('Utah');
INSERT INTO State(StateName) VALUES('Vermont');
INSERT INTO State(StateName) VALUES('Virginia');
INSERT INTO State(StateName) VALUES('Washington');
INSERT INTO State(StateName) VALUES('West Virginia');
INSERT INTO State(StateName) VALUES('Wisconsin');
INSERT INTO State(StateName) VALUES('Wyoming');
INSERT INTO State(StateName) VALUES('District of Columbia');